menu:
  首页: /
  公告: /archives

widgets:
- search

cover:
  enable: true
  url: http://yfdocument.qiniudn.com/pattern.png

excerpt_link: Read More

full_format: 'ddd, MMM D YYYY, h:mm:ss a'

growingio_analytics: 984266f00491a1b4

addthis:
  enable: true
  #pubid:
  #facebook:
  #twitter:
  #google: true
  #pinterest:
fancybox: true

rss:

comment_provider: duoshuo


# Duoshuo comment
duoshuo:
  short_name: MR.Fan

social:
  github: https://github.com/yfsoftcn
  #weibo: http://weibo.com/your_name

auto_change:
  enable: true